#Generated Form Function
function GenerateForm {
    ########################################################################
    # Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
    # Generated On: 07.10.2023 12:47
    # Generated By: Nicolas
    ########################################################################
    
    #region Import the Assemblies
    [reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
    [reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
    #endregion
    
    #region Generated Form Objects
    $F_Main = New-Object System.Windows.Forms.Form
    $GB_FileCopy = New-Object System.Windows.Forms.GroupBox
    $textBox4 = New-Object System.Windows.Forms.TextBox
    $richTextBox1 = New-Object System.Windows.Forms.RichTextBox
    $label5 = New-Object System.Windows.Forms.Label
    $GB_Files = New-Object System.Windows.Forms.GroupBox
    $TB_ProjectName = New-Object System.Windows.Forms.TextBox
    $LB_ProjectName = New-Object System.Windows.Forms.Label
    $TB_ProjectPath = New-Object System.Windows.Forms.TextBox
    $L_ProjectPath = New-Object System.Windows.Forms.Label
    $TB_ImagesPath = New-Object System.Windows.Forms.TextBox
    $L_ImagePath = New-Object System.Windows.Forms.Label
    $L_Title = New-Object System.Windows.Forms.Label
    $saveFileDialog1 = New-Object System.Windows.Forms.SaveFileDialog
    $InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
    #endregion Generated Form Objects
    
    #----------------------------------------------
    #Generated Event Script Blocks
    #----------------------------------------------
    #Provide Custom Code for events specified in PrimalForms.
    $handler_L_ProjectPath_Click= 
    {
    #TODO: Place custom script here
    
    }
    
    $handler_GB_Files_Enter= 
    {
    #TODO: Place custom script here
    
    }
    
    $handler_TB_ImagesPath_TextChanged= 
    {
    #TODO: Place custom script here
    
    }
    
    $handler_label1_Click= 
    {
    #TODO: Place custom script here
    
    }
    
    $handler_tTB_Project_TextChanged= 
    {
    #TODO: Place custom script here
    
    }
    
    $handler_L_ImagePath_Click= 
    {
    #TODO: Place custom script here
    
    }
    
    $OnLoadForm_StateCorrection=
    {#Correct the initial state of the form to prevent the .Net maximized form issue
        $F_Main.WindowState = $InitialFormWindowState
    }
    
    #----------------------------------------------
    #region Generated Form Code
    $F_Main.BackColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 338
    $System_Drawing_Size.Width = 976
    $F_Main.ClientSize = $System_Drawing_Size
    $F_Main.DataBindings.DefaultDataSourceUpdateMode = 0
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 377
    $System_Drawing_Size.Width = 992
    $F_Main.MinimumSize = $System_Drawing_Size
    $F_Main.Name = "F_Main"
    $F_Main.Text = "Primal Form"
    
    
    $GB_FileCopy.DataBindings.DefaultDataSourceUpdateMode = 0
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 13
    $System_Drawing_Point.Y = 221
    $GB_FileCopy.Location = $System_Drawing_Point
    $GB_FileCopy.Name = "GB_FileCopy"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 109
    $System_Drawing_Size.Width = 951
    $GB_FileCopy.Size = $System_Drawing_Size
    $GB_FileCopy.TabIndex = 2
    $GB_FileCopy.TabStop = $False
    $GB_FileCopy.Text = "Copie des fichiers"
    
    $F_Main.Controls.Add($GB_FileCopy)
    $textBox4.DataBindings.DefaultDataSourceUpdateMode = 0
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 239
    $System_Drawing_Point.Y = 26
    $textBox4.Location = $System_Drawing_Point
    $textBox4.Name = "textBox4"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 20
    $System_Drawing_Size.Width = 83
    $textBox4.Size = $System_Drawing_Size
    $textBox4.TabIndex = 2
    $textBox4.Text = "10"
    
    $GB_FileCopy.Controls.Add($textBox4)
    
    $richTextBox1.DataBindings.DefaultDataSourceUpdateMode = 0
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 26
    $System_Drawing_Point.Y = 51
    $richTextBox1.Location = $System_Drawing_Point
    $richTextBox1.Name = "richTextBox1"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 45
    $System_Drawing_Size.Width = 905
    $richTextBox1.Size = $System_Drawing_Size
    $richTextBox1.TabIndex = 1
    $richTextBox1.Text = "Le programme va attendre un délai définit après chaque nouvelle photographie prise. Si aucune nouvelle photographie n''est faite durant ce délai, le scan 3D peut démarrer. C''est utilisé pour la synchronisation automatique des images depuis la caméra en MTP."
    
    $GB_FileCopy.Controls.Add($richTextBox1)
    
    $label5.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 21
    $System_Drawing_Point.Y = 29
    $label5.Location = $System_Drawing_Point
    $label5.Name = "label5"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 237
    $label5.Size = $System_Drawing_Size
    $label5.TabIndex = 0
    $label5.Text = "Délai (sec) avant de commencer le scan"
    
    $GB_FileCopy.Controls.Add($label5)
    
    
    
    $GB_Files.DataBindings.DefaultDataSourceUpdateMode = 0
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 13
    $System_Drawing_Point.Y = 66
    $GB_Files.Location = $System_Drawing_Point
    $GB_Files.Name = "GB_Files"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 148
    $System_Drawing_Size.Width = 951
    $GB_Files.Size = $System_Drawing_Size
    $GB_Files.TabIndex = 1
    $GB_Files.TabStop = $False
    $GB_Files.Text = "Fichiers"
    $GB_Files.add_Enter($handler_GB_Files_Enter)
    
    $F_Main.Controls.Add($GB_Files)
    $TB_ProjectName.DataBindings.DefaultDataSourceUpdateMode = 0
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 185
    $System_Drawing_Point.Y = 112
    $TB_ProjectName.Location = $System_Drawing_Point
    $TB_ProjectName.Name = "TB_ProjectName"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 20
    $System_Drawing_Size.Width = 177
    $TB_ProjectName.Size = $System_Drawing_Size
    $TB_ProjectName.TabIndex = 5
    $TB_ProjectName.Text = "3D_Scan"
    
    $GB_Files.Controls.Add($TB_ProjectName)
    
    $LB_ProjectName.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 21
    $System_Drawing_Point.Y = 112
    $LB_ProjectName.Location = $System_Drawing_Point
    $LB_ProjectName.Name = "LB_ProjectName"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 158
    $LB_ProjectName.Size = $System_Drawing_Size
    $LB_ProjectName.TabIndex = 4
    $LB_ProjectName.Text = "Nom du projet"
    
    $GB_Files.Controls.Add($LB_ProjectName)
    
    $TB_ProjectPath.DataBindings.DefaultDataSourceUpdateMode = 0
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 185
    $System_Drawing_Point.Y = 74
    $TB_ProjectPath.Location = $System_Drawing_Point
    $TB_ProjectPath.Name = "TB_ProjectPath"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 20
    $System_Drawing_Size.Width = 698
    $TB_ProjectPath.Size = $System_Drawing_Size
    $TB_ProjectPath.TabIndex = 3
    $TB_ProjectPath.add_TextChanged($handler_tTB_Project_TextChanged)
    
    $GB_Files.Controls.Add($TB_ProjectPath)
    
    $L_ProjectPath.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 21
    $System_Drawing_Point.Y = 74
    $L_ProjectPath.Location = $System_Drawing_Point
    $L_ProjectPath.Name = "L_ProjectPath"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 21
    $System_Drawing_Size.Width = 158
    $L_ProjectPath.Size = $System_Drawing_Size
    $L_ProjectPath.TabIndex = 2
    $L_ProjectPath.Text = "Path de sauvegarde du projet"
    $L_ProjectPath.add_Click($handler_L_ProjectPath_Click)
    
    $GB_Files.Controls.Add($L_ProjectPath)
    
    $TB_ImagesPath.DataBindings.DefaultDataSourceUpdateMode = 0
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 185
    $System_Drawing_Point.Y = 35
    $TB_ImagesPath.Location = $System_Drawing_Point
    $TB_ImagesPath.Name = "TB_ImagesPath"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 20
    $System_Drawing_Size.Width = 698
    $TB_ImagesPath.Size = $System_Drawing_Size
    $TB_ImagesPath.TabIndex = 1
    $TB_ImagesPath.add_TextChanged($handler_TB_ImagesPath_TextChanged)
    
    $GB_Files.Controls.Add($TB_ImagesPath)
    
    $L_ImagePath.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 21
    $System_Drawing_Point.Y = 35
    $L_ImagePath.Location = $System_Drawing_Point
    $L_ImagePath.Name = "L_ImagePath"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 21
    $System_Drawing_Size.Width = 158
    $L_ImagePath.Size = $System_Drawing_Size
    $L_ImagePath.TabIndex = 0
    $L_ImagePath.Text = "Path des images"
    $L_ImagePath.add_Click($handler_L_ImagePath_Click)
    
    $GB_Files.Controls.Add($L_ImagePath)
    
    
    $L_Title.Anchor = 13
    $L_Title.BackColor = [System.Drawing.Color]::FromArgb(0,255,255,255)
    $L_Title.DataBindings.DefaultDataSourceUpdateMode = 0
    $L_Title.Font = New-Object System.Drawing.Font("Source Code Pro Black",26.2499981,1,3,0)
    $L_Title.ForeColor = [System.Drawing.Color]::FromArgb(255,0,0,0)
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 12
    $System_Drawing_Point.Y = 9
    $L_Title.Location = $System_Drawing_Point
    $L_Title.Name = "L_Title"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 54
    $System_Drawing_Size.Width = 952
    $L_Title.Size = $System_Drawing_Size
    $L_Title.TabIndex = 0
    $L_Title.Text = "MTP Automatic Photogrammetry"
    $L_Title.TextAlign = 2
    $L_Title.add_Click($handler_label1_Click)
    
    $F_Main.Controls.Add($L_Title)
    
    $saveFileDialog1.CreatePrompt = $True
    $saveFileDialog1.InitialDirectory = "C:\"
    $saveFileDialog1.ShowHelp = $True
    
    #endregion Generated Form Code
    
    #Save the initial state of the form
    $InitialFormWindowState = $F_Main.WindowState
    #Init the OnLoad event to correct the initial state of the form
    $F_Main.add_Load($OnLoadForm_StateCorrection)
    #Show the Form
    $F_Main.ShowDialog()| Out-Null
    
    } #End Function
    
    #Call the Function
    GenerateForm
    